spring:
  main.banner-mode: "off"
  application.name: app
  output.ansi.enabled: always

  data:
    mongodb:
      database: app
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      repositories:
        type: REACTIVE

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      adjust-dates-to-context-time-zone: false

server:
  port: 8080

logging:
  pattern:
    level: "%clr(%-5p)"
    console: "%date{yyyy.MM.dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN} %clr([%thread]){magenta} %clr(%logger{-1}){cyan}->%clr(%method){blue}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level.root: INFO
