spring:
  main:
    banner-mode: off
    lazy-initialization: true
  application.name: app
  output.ansi.enabled: always
  jmx.enabled: false

  data:
    mongodb:
      database: app
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      repositories:
        type: REACTIVE

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      adjust-dates-to-context-time-zone: false
    default-property-inclusion: non_null

server:
  port: 8080

management:
  endpoint.health.show-details: always
  endpoints:
    enabled-by-default: true
    web.exposure.include: "health, info, env, configprops, metrics"
    jmx.exposure.exclude: "*"
  metrics.export.jmx.enabled: false

logging:
  pattern:
    level: "%clr(%-5p)"
    console: "%date{yyyy.MM.dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN} %clr([%thread]){magenta} %clr(%logger{-1}){cyan}->%clr(%method){blue}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  register-shutdown-hook: true
  level.root: INFO
