version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    image: app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
